SELECT CONCAT('/home/grep/src/',a.BOARD_ID,'/', b.FILE_ID, b.FILE_NAME ,b.FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD as a, USED_GOODS_FILE as b
WHERE a.VIEWS = (SELECT max(VIEWS) from USED_GOODS_BOARD) and a.BOARD_ID = b.BOARD_ID
ORDER BY FILE_ID desc