SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as b, USED_GOODS_USER as u
WHERE b.WRITER_ID = u.USER_ID and b.STATUS = 'DONE'
GROUP BY u.USER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES asc