SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, fp.PRICE*SUM(fo.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT fp 
INNER JOIN FOOD_ORDER fo
ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE fo.PRODUCE_DATE LIKE "2022-05%"
GROUP BY fo.PRODUCT_ID
ORDER BY TOTAL_SALES desc, PRODUCT_ID asc