SELECT DISTINCT c.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR c
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    ON c.CAR_ID = h.CAR_ID
WHERE c.CAR_TYPE = '세단' and h.START_DATE LIKE '2022-10-%'
ORDER BY c.CAR_ID desc